// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/Lyrics/save.ts";
import * as $$$$$$$$$$$0 from "./apps/deco/htmx.ts";
import * as $$$$$$$$$$$1 from "./apps/site.ts";
import * as $$$0 from "./loaders/AlbumInfo/records.ts";
import * as $$$1 from "./loaders/CoverSlider/recordsAlbuns.ts";
import * as $$$2 from "./loaders/CoverSlider/recordsAlbunsByMusic.ts";
import * as $$$3 from "./loaders/Lyrics/GetLanguages.ts";
import * as $$$4 from "./loaders/Lyrics/GetLyrics.ts";
import * as $$$5 from "./loaders/MusicData/records.ts";
import * as $$$6 from "./loaders/MusicHero/records.ts";
import * as $$$7 from "./loaders/MusicInfo/records.ts";
import * as $$$8 from "./loaders/MusicList/recordsAlbuns.ts";
import * as $$$9 from "./loaders/SeoLoader/records/album.ts";
import * as $$$10 from "./loaders/SeoLoader/records/music.ts";
import * as $$$11 from "./loaders/Translation/Translator.ts";
import * as $$$$$$0 from "./sections/AlbumInfo.tsx";
import * as $$$$$$1 from "./sections/Component.tsx";
import * as $$$$$$2 from "./sections/CoverSlider.tsx";
import * as $$$$$$3 from "./sections/Footer.tsx";
import * as $$$$$$4 from "./sections/Hero.tsx";
import * as $$$$$$5 from "./sections/HomeScrollAnimater.tsx";
import * as $$$$$$6 from "./sections/LatestRelease.tsx";
import * as $$$$$$7 from "./sections/LyricsEditor.tsx";
import * as $$$$$$8 from "./sections/LyricsSync.tsx";
import * as $$$$$$9 from "./sections/LyricsSynchronization.tsx";
import * as $$$$$$10 from "./sections/MenuDemo.tsx";
import * as $$$$$$11 from "./sections/MusicData.tsx";
import * as $$$$$$12 from "./sections/MusicHero.tsx";
import * as $$$$$$13 from "./sections/MusicInfo.tsx";
import * as $$$$$$14 from "./sections/MusicList.tsx";
import * as $$$$$$15 from "./sections/SeoLoader.tsx";
import * as $$$$$$16 from "./sections/ShowBeforeAnimation.tsx";
import * as $$$$$$17 from "./sections/Spacer.ts";
import * as $$$$$$18 from "./sections/Theme/Theme.tsx";

const manifest = {
  "loaders": {
    "site/loaders/AlbumInfo/records.ts": $$$0,
    "site/loaders/CoverSlider/recordsAlbuns.ts": $$$1,
    "site/loaders/CoverSlider/recordsAlbunsByMusic.ts": $$$2,
    "site/loaders/Lyrics/GetLanguages.ts": $$$3,
    "site/loaders/Lyrics/GetLyrics.ts": $$$4,
    "site/loaders/MusicData/records.ts": $$$5,
    "site/loaders/MusicHero/records.ts": $$$6,
    "site/loaders/MusicInfo/records.ts": $$$7,
    "site/loaders/MusicList/recordsAlbuns.ts": $$$8,
    "site/loaders/SeoLoader/records/album.ts": $$$9,
    "site/loaders/SeoLoader/records/music.ts": $$$10,
    "site/loaders/Translation/Translator.ts": $$$11,
  },
  "sections": {
    "site/sections/AlbumInfo.tsx": $$$$$$0,
    "site/sections/Component.tsx": $$$$$$1,
    "site/sections/CoverSlider.tsx": $$$$$$2,
    "site/sections/Footer.tsx": $$$$$$3,
    "site/sections/Hero.tsx": $$$$$$4,
    "site/sections/HomeScrollAnimater.tsx": $$$$$$5,
    "site/sections/LatestRelease.tsx": $$$$$$6,
    "site/sections/LyricsEditor.tsx": $$$$$$7,
    "site/sections/LyricsSync.tsx": $$$$$$8,
    "site/sections/LyricsSynchronization.tsx": $$$$$$9,
    "site/sections/MenuDemo.tsx": $$$$$$10,
    "site/sections/MusicData.tsx": $$$$$$11,
    "site/sections/MusicHero.tsx": $$$$$$12,
    "site/sections/MusicInfo.tsx": $$$$$$13,
    "site/sections/MusicList.tsx": $$$$$$14,
    "site/sections/SeoLoader.tsx": $$$$$$15,
    "site/sections/ShowBeforeAnimation.tsx": $$$$$$16,
    "site/sections/Spacer.ts": $$$$$$17,
    "site/sections/Theme/Theme.tsx": $$$$$$18,
  },
  "actions": {
    "site/actions/Lyrics/save.ts": $$$$$$$$$0,
  },
  "apps": {
    "site/apps/deco/htmx.ts": $$$$$$$$$$$0,
    "site/apps/site.ts": $$$$$$$$$$$1,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
